name: CI
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install Dependencies (API)
        working-directory: backend
        run: npm ci

      - name: Install Dependencies (Web)
        working-directory: frontend
        run: npm ci

      - name: Build Backend (API)
        working-directory: backend
        run: npm run build

      - name: Build Frontend (Web)
        working-directory: frontend
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Linter Backend (API)
        working-directory: backend
        run: |
          npm ci
          npm run lint

      - name: Linter Frontend (Web)
        working-directory: frontend
        run: |
          npm ci
          npm run lint

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
